max_width = 100
tab_spaces = 4
edition = "2021"
newline_style = "Unix"
use_small_heuristics = "Default"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
struct_field_align_threshold = 20
enum_discrim_align_threshold = 20
format_macro_bodies = true
format_macro_matchers = true
combine_control_expr = true
match_arm_blocks = false
fn_single_line = true
reorder_impl_items = true
match_block_trailing_comma = true
where_single_line = true
overflow_delimited_expr = true
trailing_comma = "Vertical"
use_field_init_shorthand = true
unstable_features = true
